# Generated by Django 4.2.5 on 2024-05-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
